### ISSUE TITLE
Logging statement error

### ISSUE THREAD

**Issue by grempe** [mlewis7127/qldb-simple-demo#2]
Firstly, thank you. This example repo was extremely helpful and your timing couldn't have been better.

I noticed an issue with one of the logging statements:

https://github.com/mlewis7127/qldb-simple-demo/blob/master/functions/createIndex.js#L39

Which refers to the creation of a table, but it should actually be for the creation of an index and include the `tableName` and `indexAttribute`.

Cheers

**Comment by mlewis7127** [comment]
Hi there. Sorry I missed this. I was just updating this repo today to take into account latest updates to the Nodejs driver. I fixed the logging statement on `createIndex` that you noticed as well. Thanks for pointing out

**Comment by grempe** [comment]
PS - The new streams code example  is 🔥
